#!/usr/bin/env python
#
# This file is part of sspkd.
#
# sspkd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sspkd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with sspkd.  If not, see <http://www.gnu.org/licenses/>.
#
import sspkd
import sys

if len(sys.argv) < 2:
    print "Usage: %s (<filename>|--install)" % sys.argv[0]
    sys.exit(3)

try:
    if sys.argv[1] == '--install':
        sspkd.fetch(install=True)
    else:
        with open(sys.argv[1], "w") as f:
            f.write(sspkd.fetch())
except Exception, e:
    print "error: %s" % e.message 
