#!/usr/bin/env python
#
# This file is part of sspkd.
#
# sspkd is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# sspkd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with sspkd.  If not, see <http://www.gnu.org/licenses/>.
#
import sspkd
import sys

try:
    if len(sys.argv) < 2:
        raise Exception("no command given")
    
    if sys.argv[1] == 'receive':
        sspkd.recv(sys.stdin.read())
    elif sys.argv[1] == 'fetch':
        print sspkd.fetch(verify=False)
    else:
        raise Exception("unknown command: %s" % sys.argv[1])

except Exception, e:
    print "error: %s" % e.message
